services:
  web:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    # environment: 
    #   - FLASK_SERVER_ADDR=backend:5328  
    # command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 8080:80
      - 443:443
    depends_on:
      - backend

  backend:
    build:
      context: pepe-silvia
      # target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - 5328:5328
    environment:
      - FLASK_SERVER_PORT=5328
    volumes:
     - type: bind
       source: ./.aws
       target: /pepe-silvia/.aws
    #  - type: bind
    #    source: ./app/.env
    #    target: /app
    #  - ./app:/app
    # volumes:

